PromotionsPrototypeApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PromotionsPrototypeApp.Models;

namespace PromotionsPrototypeApp.Controllers
{
    public class ProductController : Controller
    {
        private Entities db = new Entities();

        // GET: Product
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.SpecialOffer);
            return View(products.ToList());
        }

        public ActionResult Store()
        {
            ViewBag.productList = db.Products.ToList();
            return View("Store");
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.SpecialOfferID = new SelectList(db.SpecialOffers, "ID", "Name");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,SpecialOfferID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SpecialOfferID = new SelectList(db.SpecialOffers, "ID", "Name", product.SpecialOfferID);
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.SpecialOfferID = new SelectList(db.SpecialOffers, "ID", "Name", product.SpecialOfferID);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,SpecialOfferID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SpecialOfferID = new SelectList(db.SpecialOffers, "ID", "Name", product.SpecialOfferID);
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PromotionsPrototypeApp/Controllers/ShoppingCartController.cs
using MoreLinq;
using PromotionsPrototypeApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PromotionsPrototypeApp.Controllers
{
    public class ShoppingCartController : Controller
    {
        Entities db = new Entities();

        public ActionResult Index()
        {
            if (Session["cart"] == null)
                Session["cart"] = new List<Item>();

            return View("Cart");
        }

        public ActionResult AddProduct(int id)
        {
            List<Item> cart;

            if (Session["cart"] == null)
                cart = new List<Item>();
            else
                cart = (List<Item>)Session["cart"];

            Product product = db.Products.Find(id);
            Item item = new Item(product);

            cart.Add(item);

            UpdateCartDiscounts(cart, item);

            Session["cart"] = cart;

            return View("Cart");
        }

        public ActionResult RemoveProduct(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            Item productItem = cart[cart.FindLastIndex(x => x.Product.ID == id)];

            cart.Remove(productItem);

            UpdateCartDiscounts(cart, productItem);

            Session["cart"] = cart;
            return View("Cart");
        }

        private void UpdateCartDiscounts(List<Item> cart, Item item)
        {
            SpecialOffer specialOffer = item.Product.SpecialOffer;

            if(specialOffer != null)
            {
                var productItems = cart.Where(x => x.Product.ID == item.Product.ID).ToList();
                var itemsBatch = productItems.Batch(specialOffer.ItemsMinimumNumber.Value).ToList();

                foreach (Item[] batchProductItems in itemsBatch)
                {
                    if (batchProductItems.Count() == specialOffer.ItemsMinimumNumber.Value)
                        batchProductItems.ForEach(p => p.SalesPrice = p.Product.Price - (p.Product.Price * (decimal)specialOffer.Discount));
                    else
                        batchProductItems.ForEach(p => p.SalesPrice = p.Product.Price);
                }
            }            
        }
    }
}

PromotionsPrototypeApp/Views/Product/Create.cshtml
@model PromotionsPrototypeApp.Models.Product

@{
    ViewBag.Title = "Criar";
}

<h2>Criar produto</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialOfferID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpecialOfferID", null, "Selecione", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecialOfferID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar", "Index")
</div>

PromotionsPrototypeApp/Views/Product/Delete.cshtml
@model PromotionsPrototypeApp.Models.Product

@{
    ViewBag.Title = "Exclusão";
}

<h2>Excluir produto</h2>

<h3>Você tem certeza que deseja excluir este produto?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialOffer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialOffer.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Retornar", "Index")
        </div>
    }
</div>

PromotionsPrototypeApp/Views/Product/Details.cshtml
@model PromotionsPrototypeApp.Models.Product

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhar produto</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialOffer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialOffer.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Retornar", "Index")
</p>

PromotionsPrototypeApp/Views/Product/Edit.cshtml
@model PromotionsPrototypeApp.Models.Product

@{
    ViewBag.Title = "Editar";
}

<h2>Editar produto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialOfferID, "Promoção", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpecialOfferID", null, "Selecione", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecialOfferID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar", "Index")
</div>

PromotionsPrototypeApp/Views/Product/Index.cshtml
@model IEnumerable<PromotionsPrototypeApp.Models.Product>

@{
    ViewBag.Title = "Início";
}

<h2>Início</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpecialOffer.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpecialOffer.Name)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.ID }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>


<p>
    @Html.ActionLink("Criar novo produto", "Create")
</p>

PromotionsPrototypeApp/Views/Product/Store.cshtml
@using PromotionsPrototypeApp.Models

@{
    ViewBag.Title = "Loja";
}


<h2>Loja</h2>
<table class="table table-bordered">
    <tr>
        <th>Item</th>
        <th>Preço</th>
        <th>Promoção</th>
        <th>Comprar</th>
    </tr>
    @foreach (Product p in (List<Product>)ViewBag.productList)
    {
        <tr>
            <td>@p.Name</td>
            <td>@(string.Format("{0:C}", p.Price))</td>
            <td>@Html.DisplayFor(m => p.SpecialOffer.Name)</td>
            <td>@Html.ActionLink("Comprar", "AddProduct", "ShoppingCart", new { id = p.ID }, null)</td>
        </tr>
    }
</table>